### ISSUE TITLE
Better method to fetch available languages

### ISSUE THREAD

**Issue by wozeparrot** [Nathan13888/CodeRunnerBot#4]
piston has a [`/runtimes`](https://emkc.org/api/v2/piston/runtimes) endpoint that can be used to fetch the available language runtimes and their aliases. 
go-piston also supports this endpoint natively.

Consider switching the hard-coded [languages](https://github.com/Nathan13888/CodeRunnerBot/blob/54a15e8707bd399690a5ac8dd305c65e293a4154/bot.go#L166-L244) to use this endpoint instead.

**Comment by Nathan13888** [comment]
Will do... eventually

**Comment by vidhanio** [comment]
I can take this on?
